import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import localFont from 'next/font/local';
// import local from '@/fonts/'


// Import the font from the public directory
// const clashVariable = localFont({
//   src: "@/fonts/ClashDisplay-Variable.ttf",  // Path relative to the public folder
//   variable: "--clashVariable"
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}` }>
        {children}
      </body>
    </html>
  );
}
